def exploration(df):
    print()
    print('--------------------------')
    print('Aperçu du DataFrame (head)')
    print('-------------------------- \n')
    print(df.head(), '\n')
    print('------------------------------------')
    print('Aperçu de la fin du DataFrame (tail)')
    print('------------------------------------ \n')
    print(df.tail(), '\n')
    print('---------------------------------')
    print('Échantillon du DataFrame (sample)')
    print('--------------------------------- \n')
    print(df.sample(5), '\n')
    print('---------------------------------------')
    print('Nombre de lignes et de colonnes (shape)')
    print('--------------------------------------- \n')
    print(df.shape, '\n')
    print('-------------------------')
    print('Type des données (dtypes)')
    print('------------------------- \n')
    print(df.dtypes, '\n')
    print('------------')
    print('Infos (info)')
    print('------------ \n')
    print(df.info(), '\n')
    print('----------------------------')
    print('Nombre de NaN (isna().sum())')
    print('---------------------------- \n')
    print(df.isna().sum(), '\n')
    print('--------------------------------------')
    print('Affichage des Nan (isna().any(axis=1))')
    print('-------------------------------------- \n')
    print(df[df.isna().any(axis=1)], '\n')
    print('---------------------------------------')
    print('Nombre de doublons (duplicated().sum())')
    print('--------------------------------------- \n')
    print(df.duplicated().sum(), '\n')
    print('-----------------------------------------------------')
    print('Affichage des doublons (df[df.duplicated()].head(10))')
    print('----------------------------------------------------- \n')
    print(df[df.duplicated()].head(10), '\n')      
    print('-----------------------------------')
    print('Résumé analyse univariée (describe)')
    print('----------------------------------- \n')
    print(df.describe(include='all'))
